version: "2"

services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile-production
    expose:
      - "5000"
    links:
      - dynamodb
      - postgresql
    environment:
      NODE_ENV: production
    volumes:
      - /home/bleve:/home/bleve
    command: web run
    restart: always

  imageserver:
    build: ./imageserver
    environment:
      NODE_ENV: production
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_REGION: us-east-1
      S3_BUCKET: xxx_store
    expose:
      - "3001"
    command: npm start
    restart: always

  crawler:
    build: ./crawler
    command: bash -c "cron && tail -f /var/log/cron.log"

  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile-production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - web
      - imageserver

  redis:
    image: redis:3.0.7-alpine
    expose:
      - "6379"
    volumes:
      - /home/redis:/data
    restart: always

  postgresql:
    build: ./postgresql/
    expose:
      - "5432"
    restart: always

  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    expose:
      - "8000"
    restart: always