Port= 5000
AWSDefaultRegion= us-west-2
AWSAccessKeyID= 
AWSSecretKey= 
AWSToken=
BucketRegion= us-east-1
Bucket= 
ImageBucket= xxxcommunity-images
TemplateDir= server/data/templates
AppLogo= https://xxxinafrica.com/static/images/logo.png
AppURL= https://xxxinafrica.com
AppName= 
AppIcon= https://xxxinafrica.com/favicon.ico
Secret= Z29sZDU5
SMTPUser= admin@xxxinafrica.com
SMTPPswd= 
SMTPHost= smtp.gmail.com
SMTPPort= 587
SMTPAddr= admin@xxxinafrica.com
FileDB= files
NumWorkers= 100
GoogleAPIKey= 
certFile= /etc/letsencrypt/live/xxxinafrica.com/cert.pem
keyFile= /etc/letsencrypt/live/xxxinafrica.com/privkey.pem
chainFile= /etc/letsencrypt/live/xxxinafrica.com/chain.pem
BleveIndexPath= /home/bleve/jobs.bleve