FROM nginx:alpine
ADD sites-enabled-production/ /etc/nginx/sites-enabled
COPY nginx.conf /etc/nginx/nginx.conf
COPY dhparam.pem /etc/ssl/certs/dhparam.pem

COPY ssl-params.conf /etc/nginx/snippets/ssl-params.conf