package engine

import (
	"github.com/fanky5g/xxxinafrica/crawler/log"
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

var (
	re = BuildCityMatcher()
)

// MapRegionAndCity maps descriptions to regions
func MapRegionAndCity(description string) (string, string) {
	if re.MatchString(description) {
		city := strings.TrimSpace(re.FindStringSubmatch(description)[0])
		if _, ok := cityToRegion[strings.ToLower(city)]; ok {
			return cityToRegion[strings.ToLower(city)], city
		}
	}

	return "", ""
}

// BuildCityMatcher returns regex expression to match the major cities
func BuildCityMatcher() *regexp.Regexp {
	file, err := os.Open("cities.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()
	regexString := `(?i)`

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		regexString = fmt.Sprintf(`%s[[:blank:]]%s\b|`, regexString, strings.TrimSpace(scanner.Text()))
	}

	if err := scanner.Err(); err != nil {
		log.Fatal(err)
	}

	// remove last |
	regexString = strings.TrimSuffix(regexString, "|")
	return regexp.MustCompile(regexString)
}

var (
	cityToRegion = map[string]string{
		"ababio":                          "greater accra",
		"abeka":                           "greater accra",
		"abetinso":                        "greater accra",
		"ablajei":                         "greater accra",
		"ablefu":                          "greater accra",
		"ablekuma":                        "greater accra",
		"ablemkpe":                        "greater accra",
		"ablenkpe":                        "greater accra",
		"aboansa":                         "greater accra",
		"aboansa number 2":                "greater accra",
		"abochiman":                       "greater accra",
		"abofu":                           "greater accra",
		"abokobi":                         "greater accra",
		"aboman":                          "greater accra",
		"abossey okai":                    "greater accra",
		"abosumba":                        "greater accra",
		"abrekuma":                        "greater accra",
		"abura":                           "greater accra",
		"accra":                           "greater accra",
		"accra centra":                    "greater accra",
		"accra new town":                  "greater accra",
		"achiaman":                        "greater accra",
		"achimota":                        "greater accra",
		"achimota forest":                 "greater accra",
		"achimota village":                "greater accra",
		"adabraka":                        "greater accra",
		"adaiso":                          "greater accra",
		"addogonno":                       "greater accra",
		"adembra":                         "greater accra",
		"adenkrebi":                       "greater accra",
		"adentan":                         "greater accra",
		"adiembra":                        "greater accra",
		"adofin":                          "greater accra",
		"adusa":                           "greater accra",
		"adzenkotoku":                     "greater accra",
		"afiaman":                         "greater accra",
		"afianya":                         "greater accra",
		"afuaman":                         "greater accra",
		"agblesia":                        "greater accra",
		"agbogba":                         "greater accra",
		"agbogbloshie":                    "greater accra",
		"agboogba":                        "greater accra",
		"ahinkro":                         "greater accra",
		"ahireso":                         "greater accra",
		"ahunju":                          "greater accra",
		"aidan":                           "greater accra",
		"aikaidoboro":                     "greater accra",
		"airport hills residential area":  "greater accra",
		"airport residential area":        "greater accra",
		"aiyim":                           "greater accra",
		"aiyimensa":                       "greater accra",
		"ajenkotoku":                      "greater accra",
		"ajerkotuku":                      "greater accra",
		"ajimenti":                        "greater accra",
		"ajiringano":                      "greater accra",
		"akkr":                            "greater accra",
		"akkra":                           "greater accra",
		"akokome":                         "greater accra",
		"akomato":                         "greater accra",
		"akotoshi":                        "greater accra",
		"akotuaku":                        "greater accra",
		"akpoman":                         "greater accra",
		"akra":                            "greater accra",
		"akra, gana":                      "greater accra",
		"akrabon":                         "greater accra",
		"akrabon ahentsia":                "greater accra",
		"akrabon kwa tete":                "greater accra",
		"akrabong":                        "greater accra",
		"akrabong joma":                   "greater accra",
		"akramaman":                       "greater accra",
		"akraman":                         "greater accra",
		"akramang":                        "greater accra",
		"akramoman":                       "greater accra",
		"akrao":                           "greater accra",
		"akropon":                         "greater accra",
		"akropong":                        "greater accra",
		"akubrefa":                        "greater accra",
		"akutase medie":                   "greater accra",
		"akwaman":                         "greater accra",
		"akwechi":                         "greater accra",
		"akweiman":                        "greater accra",
		"akwetema":                        "greater accra",
		"akweteyman":                      "greater accra",
		"akweti":                          "greater accra",
		"akwetsi":                         "greater accra",
		"aladzo":                          "greater accra",
		"alajo":                           "greater accra",
		"algoboshie":                      "greater accra",
		"amamole":                         "greater accra",
		"amamoli":                         "greater accra",
		"amamorley":                       "greater accra",
		"amanfro":                         "greater accra",
		"amasaman":                        "greater accra",
		"amedua":                          "greater accra",
		"amontidom":                       "greater accra",
		"amrahia":                         "greater accra",
		"amuanda":                         "greater accra",
		"anafro":                          "greater accra",
		"ankwadoboro":                     "greater accra",
		"anoti":                           "greater accra",
		"anumle":                          "greater accra",
		"anunmle":                         "greater accra",
		"anyino":                          "greater accra",
		"apapa":                           "greater accra",
		"apenkwa":                         "greater accra",
		"aplaku":                          "greater accra",
		"apoloni":                         "greater accra",
		"apomasi":                         "greater accra",
		"aprachiri":                       "greater accra",
		"aprachiri awuna kwame":           "greater accra",
		"aprakyir":                        "greater accra",
		"apreweti":                        "greater accra",
		"asabaham":                        "greater accra",
		"asamoa":                          "greater accra",
		"asebu":                           "greater accra",
		"ashaaladza":                      "greater accra",
		"ashaiman":                        "greater accra",
		"ashaladza botchway":              "greater accra",
		"ashalaja":                        "greater accra",
		"ashale anan":                     "greater accra",
		"ashalebotwe":                     "greater accra",
		"ashalianan":                      "greater accra",
		"ashieye":                         "greater accra",
		"ashonman":                        "greater accra",
		"ashouman":                        "greater accra",
		"ashwenanmo":                      "greater accra",
		"ashwenanyo":                      "greater accra",
		"asikaisu":                        "greater accra",
		"asikasu":                         "greater accra",
		"asofa":                           "greater accra",
		"asokrochona":                     "greater accra",
		"asuaba":                          "greater accra",
		"asuaba number 2":                 "greater accra",
		"asuaba number 3":                 "greater accra",
		"asumen":                          "greater accra",
		"asuobonta":                       "greater accra",
		"asuokyene":                       "greater accra",
		"asuom":                           "greater accra",
		"asuom number 1":                  "greater accra",
		"asylum down":                     "greater accra",
		"atakwa":                          "greater accra",
		"atoman":                          "greater accra",
		"augustinesbor":                   "greater accra",
		"awchioma":                        "greater accra",
		"awoshie":                         "greater accra",
		"awudome estate":                  "greater accra",
		"awuku":                           "greater accra",
		"awutu":                           "greater accra",
		"ayaso":                           "greater accra",
		"ayido":                           "greater accra",
		"ayikai doblo":                    "greater accra",
		"ayim":                            "greater accra",
		"baafa number 1":                  "greater accra",
		"babafa":                          "greater accra",
		"babafa number 1":                 "greater accra",
		"badija":                          "greater accra",
		"banana inn":                      "greater accra",
		"bantama":                         "greater accra",
		"bawaleshi":                       "greater accra",
		"bawjiasi":                        "greater accra",
		"bebianeha":                       "greater accra",
		"bebianiha":                       "greater accra",
		"berekuso":                        "greater accra",
		"birekuso":                        "greater accra",
		"biuasi":                          "greater accra",
		"biwadze":                         "greater accra",
		"bleman":                          "greater accra",
		"bodomasi":                        "greater accra",
		"bodwoase":                        "greater accra",
		"boedum":                          "greater accra",
		"boi":                             "greater accra",
		"bontrase":                        "greater accra",
		"bontrasi":                        "greater accra",
		"bortianor":                       "greater accra",
		"botamfa":                         "greater accra",
		"botiana":                         "greater accra",
		"botianaw":                        "greater accra",
		"botokura":                        "greater accra",
		"bowenum":                         "greater accra",
		"brayenda":                        "greater accra",
		"bruburam":                        "greater accra",
		"buade":                           "greater accra",
		"bubiashie":                       "greater accra",
		"buduatta":                        "greater accra",
		"buduburam":                       "greater accra",
		"bunmu":                           "greater accra",
		"burma camp":                      "greater accra",
		"buruata":                         "greater accra",
		"busomabina":                      "greater accra",
		"cantonments":                     "greater accra",
		"chantan":                         "greater accra",
		"chinankama":                      "greater accra",
		"chokome":                         "greater accra",
		"chorkor":                         "greater accra",
		"christian village":               "greater accra",
		"christians village":              "greater accra",
		"christiansborg":                  "greater accra",
		"chwerebuana":                     "greater accra",
		"chwinto":                         "greater accra",
		"dabanyin":                        "greater accra",
		"dabeyin":                         "greater accra",
		"dadija":                          "greater accra",
		"dakuyau":                         "greater accra",
		"dakuyau number1":                 "greater accra",
		"dam":                             "greater accra",
		"damfa":                           "greater accra",
		"danchira":                        "greater accra",
		"danfa":                           "greater accra",
		"dankwakroa":                      "greater accra",
		"dankwakrom":                      "greater accra",
		"danso":                           "greater accra",
		"dansoman estate":                 "greater accra",
		"dantsera":                        "greater accra",
		"darkuman":                        "greater accra",
		"dedeman":                         "greater accra",
		"djankrom":                        "greater accra",
		"doboro":                          "greater accra",
		"doboro dakokurom":                "greater accra",
		"doborogonno":                     "greater accra",
		"dom":                             "greater accra",
		"dome":                            "greater accra",
		"domeabra":                        "greater accra",
		"domenase":                        "greater accra",
		"domfaase":                        "greater accra",
		"domfase":                         "greater accra",
		"domiabra":                        "greater accra",
		"duayeden":                        "greater accra",
		"dukayaw":                         "greater accra",
		"dzorwulu":                        "greater accra",
		"dzorwulu residential area":       "greater accra",
		"east dzorwulu residential area":  "greater accra",
		"east legon residential area":     "greater accra",
		"east ridge":                      "greater accra",
		"ebron":                           "greater accra",
		"esiwukroa":                       "greater accra",
		"esuochwi":                        "greater accra",
		"ewurukwa":                        "greater accra",
		"fadziemohe":                      "greater accra",
		"fajiemohe":                       "greater accra",
		"fanchiniko":                      "greater accra",
		"fete gwa":                        "greater accra",
		"fianko":                          "greater accra",
		"fise":                            "greater accra",
		"gbawe":                           "greater accra",
		"gbegbe":                          "greater accra",
		"gbegbeyise":                      "greater accra",
		"giffard camp":                    "greater accra",
		"gonse":                           "greater accra",
		"greda estates":                   "greater accra",
		"grefi":                           "greater accra",
		"gwantenang":                      "greater accra",
		"gyantomfo kurom":                 "greater accra",
		"gyeikrodua":                      "greater accra",
		"honi":                            "greater accra",
		"honi adawroma":                   "greater accra",
		"honi seh":                        "greater accra",
		"honiachim":                       "greater accra",
		"honiatsim":                       "greater accra",
		"honise":                          "greater accra",
		"honiuchim":                       "greater accra",
		"huni":                            "greater accra",
		"industrial area":                 "greater accra",
		"jamestown":                       "greater accra",
		"janman":                          "greater accra",
		"jeikrodrua":                      "greater accra",
		"jeikrodua":                       "greater accra",
		"joma":                            "greater accra",
		"juabin":                          "greater accra",
		"la":                              "greater accra",
		"la bawalshie":                    "greater accra",
		"labadi":                          "greater accra",
		"labardi":                         "greater accra",
		"lapaz":                           "greater accra",
		"lartebiokorshi":                  "greater accra",
		"lateman":                         "greater accra",
		"legion":                          "greater accra",
		"legon":                           "greater accra",
		"loye":                            "greater accra",
		"loye bortey":                     "greater accra",
		"maamobi":                         "greater accra",
		"madina":                          "greater accra",
		"maijaw":                          "greater accra",
		"maiyera":                         "greater accra",
		"malijaw":                         "greater accra",
		"mamfam":                          "greater accra",
		"mamobi":                          "greater accra",
		"mamomom":                         "greater accra",
		"mampehia":                        "greater accra",
		"mampoase":                        "greater accra",
		"mamprobi":                        "greater accra",
		"manchiman":                       "greater accra",
		"manhean":                         "greater accra",
		"manhia":                          "greater accra",
		"manokwa":                         "greater accra",
		"mataheko":                        "greater accra",
		"mayera":                          "greater accra",
		"medina estates":                  "greater accra",
		"mensakwa":                        "greater accra",
		"mensakwaa":                       "greater accra",
		"mepeasm":                         "greater accra",
		"mepom":                           "greater accra",
		"meponi":                          "greater accra",
		"mfojoboating":                    "greater accra",
		"midie":                           "greater accra",
		"milichakpo":                      "greater accra",
		"ministries":                      "greater accra",
		"minkumidie":                      "greater accra",
		"mlichakpo":                       "greater accra",
		"mpehuasem":                       "greater accra",
		"mpekadam":                        "greater accra",
		"mpuase":                          "greater accra",
		"nankanso":                        "greater accra",
		"nchechireche":                    "greater accra",
		"new achimota":                    "greater accra",
		"new fadema":                      "greater accra",
		"new mamprobi":                    "greater accra",
		"new russia":                      "greater accra",
		"nianyano":                        "greater accra",
		"niayano":                         "greater accra",
		"niiboye town":                    "greater accra",
		"nima":                            "greater accra",
		"ninyano":                         "greater accra",
		"nkotunse":                        "greater accra",
		"nkotunsi":                        "greater accra",
		"nkwantanan":                      "greater accra",
		"nkwantanang":                     "greater accra",
		"nopendaw":                        "greater accra",
		"north dzorwulu":                  "greater accra",
		"north dzorwulu residential area": "greater accra",
		"north industrial area":           "greater accra",
		"north kaneshie":                  "greater accra",
		"north labone estate":             "greater accra",
		"north ordokor":                   "greater accra",
		"north ridge":                     "greater accra",
		"nsaki":                           "greater accra",
		"nsakina":                         "greater accra",
		"nsumia":                          "greater accra",
		"nsuobri":                         "greater accra",
		"nungoa":                          "greater accra",
		"nungua":                          "greater accra",
		"nungua old town":                 "greater accra",
		"nungua salem":                    "greater accra",
		"nungwa":                          "greater accra",
		"nyanawase":                       "greater accra",
		"nyanawasi":                       "greater accra",
		"nyaniba estates":                 "greater accra",
		"nyanyano":                        "greater accra",
		"nyanyanu":                        "greater accra",
		"obakrowa":                        "greater accra",
		"obeye":                           "greater accra",
		"obeyie":                          "greater accra",
		"obiliakua":                       "greater accra",
		"oblogo":                          "greater accra",
		"oboasi":                          "greater accra",
		"obodakawa":                       "greater accra",
		"obokwashi":                       "greater accra",
		"obologo":                         "greater accra",
		"obome":                           "greater accra",
		"obotumfa":                        "greater accra",
		"obotumfo":                        "greater accra",
		"obrachere":                       "greater accra",
		"obrakrawa":                       "greater accra",
		"obrakyere":                       "greater accra",
		"obuasi":                          "greater accra",
		"obutu":                           "greater accra",
		"ochirekumfo":                     "greater accra",
		"odawmo":                          "greater accra",
		"odenki":                          "greater accra",
		"odominadzi":                      "greater accra",
		"odomponiasi":                     "greater accra",
		"odotom":                          "greater accra",
		"odotum":                          "greater accra",
		"odumase":                         "greater accra",
		"odumase number 1":                "greater accra",
		"odumasi":                         "greater accra",
		"oduntia":                         "greater accra",
		"odupon":                          "greater accra",
		"oduponkpehe":                     "greater accra",
		"odwobi":                          "greater accra",
		"ofada":                           "greater accra",
		"ofagyato nyamebedzi":             "greater accra",
		"ofako":                           "greater accra",
		"ofakor":                          "greater accra",
		"ofankor":                         "greater accra",
		"ofaso":                           "greater accra",
		"official town":                   "greater accra",
		"ofrajato":                        "greater accra",
		"ofrajato number 1":               "greater accra",
		"ogbodzo":                         "greater accra",
		"ogbojo":                          "greater accra",
		"ojubi":                           "greater accra",
		"okawso":                          "greater accra",
		"oklu":                            "greater accra",
		"oko":                             "greater accra",
		"okoman":                          "greater accra",
		"okorase":                         "greater accra",
		"okorasi":                         "greater accra",
		"okponglo":                        "greater accra",
		"okushibiade":                     "greater accra",
		"okushibiadi":                     "greater accra",
		"okusubiri":                       "greater accra",
		"okwabinabetinso":                 "greater accra",
		"okwompa":                         "greater accra",
		"old damsoman":                    "greater accra",
		"old fadama":                      "greater accra",
		"omenanokwaa":                     "greater accra",
		"onibi":                           "greater accra",
		"onibie":                          "greater accra",
		"onyachia":                        "greater accra",
		"onyansana":                       "greater accra",
		"onyansanaa":                      "greater accra",
		"opa":                             "greater accra",
		"opeikuma":                        "greater accra",
		"opeman":                          "greater accra",
		"osabo":                           "greater accra",
		"oshien":                          "greater accra",
		"oshiuman":                        "greater accra",
		"oshiyie":                         "greater accra",
		"osimpo":                          "greater accra",
		"osu":                             "greater accra",
		"otinibi":                         "greater accra",
		"otinshi":                         "greater accra",
		"otuaplem":                        "greater accra",
		"owiawosro":                       "greater accra",
		"oworatia":                        "greater accra",
		"owulabu":                         "greater accra",
		"owuraman":                        "greater accra",
		"oyamfa":                          "greater accra",
		"oyarifa":                         "greater accra",
		"oyauifa":                         "greater accra",
		"oyinso":                          "greater accra",
		"pambros salt ponds":              "greater accra",
		"pantampa":                        "greater accra",
		"pantampo":                        "greater accra",
		"pantan":                          "greater accra",
		"papao":                           "greater accra",
		"papase":                          "greater accra",
		"papase kwabina atta":             "greater accra",
		"papasi":                          "greater accra",
		"papasi number 3":                 "greater accra",
		"parakuo estates":                 "greater accra",
		"penim":                           "greater accra",
		"pig farm":                        "greater accra",
		"pobiman":                         "greater accra",
		"pokoase":                         "greater accra",
		"pokoasi":                         "greater accra",
		"pokuase":                         "greater accra",
		"poukuase":                        "greater accra",
		"ringway estate":                  "greater accra",
		"roman bridge":                    "greater accra",
		"sabon zongo":                     "greater accra",
		"sachikrom":                       "greater accra",
		"sakumona":                        "greater accra",
		"sakumono estates":                "greater accra",
		"salam":                           "greater accra",
		"samsam":                          "greater accra",
		"samsamso":                        "greater accra",
		"sansame":                         "greater accra",
		"santa maria":                     "greater accra",
		"santeo":                          "greater accra",
		"sapeman":                         "greater accra",
		"sempene":                         "greater accra",
		"serehu":                          "greater accra",
		"sesemi":                          "greater accra",
		"shiayena":                        "greater accra",
		"silehu":                          "greater accra",
		"sodom and gomorah":               "greater accra",
		"sodom and gomorrah":              "greater accra",
		"south industrial area":           "greater accra",
		"south la estate":                 "greater accra",
		"south ordokor":                   "greater accra",
		"spintex road":                    "greater accra",
		"tassi":                           "greater accra",
		"tebu":                            "greater accra",
		"teiman":                          "greater accra",
		"tema":                            "greater accra",
		"temma":                           "greater accra",
		"tenbibian":                       "greater accra",
		"tesa":                            "greater accra",
		"tesano":                          "greater accra",
		"teshi old town":                  "greater accra",
		"teshie":                          "greater accra",
		"teshie manheam":                  "greater accra",
		"teshie nungua estates":           "greater accra",
		"tete ogbu":                       "greater accra",
		"tetegbu":                         "greater accra",
		"tipai":                           "greater accra",
		"toboase":                         "greater accra",
		"toboasi":                         "greater accra",
		"tokuse":                          "greater accra",
		"tokusee":                         "greater accra",
		"toma":                            "greater accra",
		"topiase":                         "greater accra",
		"topiasi":                         "greater accra",
		"trade center":                    "greater accra",
		"tsabaa":                          "greater accra",
		"tsokome":                         "greater accra",
		"tudu":                            "greater accra",
		"tunga":                           "greater accra",
		"university of ghana":             "greater accra",
		"ussher town":                     "greater accra",
		"victoriaborg":                    "greater accra",
		"weija":                           "greater accra",
		"west legon residential":          "greater accra",
		"west ridge":                      "greater accra",
		"wiaboman":                        "greater accra",
		"wiriman":                         "greater accra",
		"yahoman":                         "greater accra",
		"yakagbomokpehe":                  "greater accra",
		"zenu":                            "greater accra",
	}
)
